name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7.2
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: RuboCop
      run: |
        bundle exec rubocop
    - name: RSpec
      run: |
        bundle exec rspec spec
